### ISSUE TITLE
syntax for http unicast

### ISSUE THREAD

**Issue by jjdisplay** [gfto/dvblast#20]
Hi

I am searching for the syntax to use dvblast for http unicast but proved futile. All the tutorials and article only showed multicast syntax.

I would appreciate it if you could show me the syntax for using dvblast for http unicast. Many thanks

**Comment by nrmmota** [comment]
Hi,
There's no syntax because there is no support.
Suggestion: stream is as udp multicast/unicast and then use VLC to do the
HTTP.

 vlc -vvv udp://@xxx.xxx.xxx.xx:xxxx --sout
'#standard{access=http,mux=ts,dst=ip:8080}'

https://wiki.videolan.org/Documentation:Streaming_HowTo/Command_Line_Examples/




jjdisplay <notifications@github.com> escreveu no dia domingo, 11/08/2019
à(s) 17:34:

**Comment by jjdisplay** [comment]
I appreciate your prompt response. Thank you.
